name: Build and Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch: # Enable manual trigger.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install Dependencies
        run: bun install
      
      - name: Build Package
        run: bun run build
        # This runs all build steps (CLI, frontend, and backend)
      
      - name: Verify Build Artifacts
        run: |
          if [ ! -d "cli-dist" ] || [ ! -d "dist" ] || [ ! -d "backend-dist" ]; then
            echo "Missing build artifacts!" && exit 1
          fi
      
      - name: Publish to npm
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}