/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SecondIndexImport } from './routes/second-index'
import { Route as IndexImport } from './routes/index'
import { Route as DetailsPairImport } from './routes/details.$pair'

// Create/Update Routes

const SecondIndexRoute = SecondIndexImport.update({
  id: '/second-index',
  path: '/second-index',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DetailsPairRoute = DetailsPairImport.update({
  id: '/details/$pair',
  path: '/details/$pair',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/second-index': {
      id: '/second-index'
      path: '/second-index'
      fullPath: '/second-index'
      preLoaderRoute: typeof SecondIndexImport
      parentRoute: typeof rootRoute
    }
    '/details/$pair': {
      id: '/details/$pair'
      path: '/details/$pair'
      fullPath: '/details/$pair'
      preLoaderRoute: typeof DetailsPairImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/second-index': typeof SecondIndexRoute
  '/details/$pair': typeof DetailsPairRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/second-index': typeof SecondIndexRoute
  '/details/$pair': typeof DetailsPairRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/second-index': typeof SecondIndexRoute
  '/details/$pair': typeof DetailsPairRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/second-index' | '/details/$pair'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/second-index' | '/details/$pair'
  id: '__root__' | '/' | '/second-index' | '/details/$pair'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecondIndexRoute: typeof SecondIndexRoute
  DetailsPairRoute: typeof DetailsPairRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecondIndexRoute: SecondIndexRoute,
  DetailsPairRoute: DetailsPairRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/second-index",
        "/details/$pair"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/second-index": {
      "filePath": "second-index.tsx"
    },
    "/details/$pair": {
      "filePath": "details.$pair.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
